// Generated by CoffeeScript 1.6.3
(function() {
  var App,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  App = function() {
    this.languages = [
      {
        'key': 'bg',
        'name': 'Bulgarian',
        'text': 'Често столицата е център на дейности от много голямо значение за страната - политически, икономически, културни и други.'
      }, {
        'key': 'cs',
        'name': 'Czech',
        'text': 'Hlavní město představuje správní středisko a symbol určitého území, typicky státu nebo většího správního nebo samosprávného celku.'
      }, {
        'key': 'en',
        'name': 'English',
        'text': 'Three supporters taken to hospital and ten more injured in brawl at city café on Sunday night after allegedly being ‘set upon’ by Ukrainian group.'
      }, {
        'key': 'mn',
        'name': 'Mongolian',
        'text': 'Дэлхийн хамгийн том хотууд нь заримдаа улсын нийслэл биш байдаг.'
      }, {
        'key': 'pt',
        'name': 'Português',
        'text': 'A flor é a estrutura reprodutora característica das plantas denominadas espermatófitas ou fanerogâmicas.'
      }
    ];
    this.run = function() {
      var i, idx, key, languages, name, names, text, _i, _len, _ref;
      languages = this.languages;
      idx = Math.floor(Math.random() * languages.length);
      key = languages[idx].key;
      name = languages[idx].name;
      text = languages[idx].text;
      names = [name];
      while (names.length < 3) {
        i = Math.floor(Math.random() * languages.length);
        if (_ref = languages[i].name, __indexOf.call(names, _ref) >= 0) {
          continue;
        }
        names.push(languages[i].name);
      }
      for (i = _i = 0, _len = names.length; _i < _len; i = ++_i) {
        name = names[i];
        $("#btn-" + i).text(name);
      }
      $('#language').text(text);
    };
  };

  jQuery(function($) {
    return new App().run();
  });

}).call(this);
